sudo: required

language: java

jdk: openjdk11

addons:
  sonarcloud:
    organization: "slobanov-github"

services:
  - docker

install: true
script: mvn clean test sonar:sonar install docker:push && ./social-network/scripts/heroku/redeploy.sh

