version: "3.7"
services:
  mysql:
    image: mysql:8.0.19
    container_name: mysql
    volumes:
      #- ./../../db-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
